# Workflow to configure with cmake and build with gcc

name: Build with gcc-11

on:
  push:
    branches: [ master, sc_release ]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout NWgr
      uses: actions/checkout@v4
      with:
        path: NWgr

    - name: Install dependencies
      run: |
        # Install Intel oneAPI TBB
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
          | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" \
          | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update
        DEBIAN_FRONTEND=noninteractive sudo apt-get -y install intel-oneapi-tbb-devel
        # Install gcc-11 (available on ubuntu-22.04+)
        DEBIAN_FRONTEND=noninteractive sudo apt-get -y install gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 90 --slave /usr/bin/g++ g++ /usr/bin/g++-11
        sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
        sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30

    - name: cmake
      run: |
        cd NWgr
        mkdir build
        cd build
        export TBBROOT=/opt/intel/oneapi/tbb/latest
        cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=g++-11 -DNWGRAPH_BUILD_DOCS=OFF -DNWGRAPH_BUILD_TESTS=ON

    - name: make
      run: |
        cd NWgr/build
        make -j -k

    - name: run_test
      run: |
        cd NWgr/build
        make test
